### ISSUE TITLE
' No Module Named Requests '

### ISSUE THREAD

**Issue by ghost** [s0md3v/Orbit#13]
Hello, I put this input into my command line : python orbit.py -s 0xaAFCBe22104766F57d1d60E169cc466697B41913 and ended up getting this output from my terminal ?

C:\Users\Admin\Downloads\Compressed\Orbit-master\Orbit-master>python orbit.py -s 0xaAFCBe22104766F57d1d60E169cc466697B41913
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Compressed\Orbit-master\Orbit-master\orbit.py", line 18, in <module>
    from core.getTransactions import getTransactions
  File "C:\Users\Admin\Downloads\Compressed\Orbit-master\Orbit-master\core\getTransactions.py", line 3, in <module>
    from core.requester import requester
  File "C:\Users\Admin\Downloads\Compressed\Orbit-master\Orbit-master\core\requester.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Would love to be able to use your tool. Thanks.

**Comment by snub-fighter** [comment]
pip install requests
